### ISSUE TITLE
Visual Studio Code (vscode) does not see WooCommerce-Core

### ISSUE THREAD

**Issue by iaroslavglodov** [woocommerce/woocommerce-sniffs#17] opened 2021-03-19 18:57 UTC
Please provide an example of installation of the sniffs for Visual Studio Code.

I have installed them and defined in the workspace configuration but it shows an error: `phpcs: The "WooCommerce-Core" coding standard is not installed. Please review your configuration an try again.`

My `composer.json` file:
```json
{
    "require-dev": {
        "wp-coding-standards/wpcs": "2.3.0",
        "squizlabs/php_codesniffer": "3.*"
    },
    "scripts": {
        "post-install-cmd": [
            "\"vendor/bin/phpcs\" --config-set installed_paths vendor/wp-coding-standards/wpcs"
        ],
        "post-update-cmd": [
            "\"vendor/bin/phpcs\" --config-set installed_paths vendor/wp-coding-standards/wpcs"
        ]
    },
    "require": {
        "woocommerce/woocommerce-sniffs": "^0.1.0"
    }
}
```

My `project.code-workspace` file:
```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"phpcs.enable": true,
		"phpcs.standard": "WooCommerce-Core",
		"phpcs.executablePath": "vendor/bin/phpcs",
		"phpcs.showWarnings": true,
		"phpcs.composerJsonPath": "composer.json",
		"phpcs.errorSeverity": 5,
		"php.suggest.basic": true,
		"phpcs.lintOnType": false,
		"editor.insertSpaces": false
	}
}
```

**Comment by claudiosanches** [comment] 2021-07-29 17:18
I can't reproduce this error, works great on VSCode, you can also check with `./vendor/bin/phpcs -i` to see the list of installed coding standards.

I'm closing since it works as expected, and it follows PHP_CodeSniffer documentation.

**Closed as completed by claudiosanches** 2021-07-29 17:18 UTC
